# Run from: C:\Users\nehad\AgriLeaf_Local\agrileaf\
# Command: python fix_pdf.py

with open('frontend/static/js/main.js', 'r', encoding='utf-8') as f:
    js = f.read()

# Find and replace the entire downloadReport function
import re
start = js.find('function downloadReport()')
end = js.find('\nfunction ', start + 1)
if end == -1:
    end = js.find('\nasync function ', start + 1)

old_fn = js[start:end]

new_fn = """function downloadReport() {
    var disease  = document.getElementById('resultDisease') ? document.getElementById('resultDisease').textContent : 'Unknown';
    var meta     = document.getElementById('resultMeta') ? document.getElementById('resultMeta').textContent : '';
    var conf     = document.getElementById('confidenceNum') ? document.getElementById('confidenceNum').textContent : '';
    var sevChip  = document.querySelector('.severity-chip');
    var severity = sevChip ? sevChip.textContent : '';
    var desc     = document.getElementById('diseaseDesc') ? document.getElementById('diseaseDesc').textContent : '';
    var treat    = document.getElementById('treatList') ? document.getElementById('treatList').innerText : '';
    var now      = new Date().toLocaleString('en-IN');

    var html = '<!DOCTYPE html><html><head><meta charset="UTF-8"><title>AgriLeaf Report</title>' +
        '<style>body{font-family:Georgia,serif;max-width:700px;margin:40px auto;color:#1a1a1a;padding:0 20px}' +
        '.header{background:#1a3d2b;color:#fff;padding:28px 32px;border-radius:12px;margin-bottom:28px}' +
        '.header h1{margin:0;font-size:22px}.header p{margin:6px 0 0;opacity:.75;font-size:13px}' +
        '.badge{display:inline-block;background:rgba(255,255,255,.15);padding:4px 12px;border-radius:20px;font-size:12px;margin-top:10px}' +
        '.section{margin-bottom:24px;padding:20px 24px;border:1.5px solid #e5e7eb;border-radius:10px}' +
        '.section h3{margin:0 0 12px;font-size:13px;text-transform:uppercase;letter-spacing:1px;color:#2d6a4f}' +
        '.row{display:flex;justify-content:space-between;margin-bottom:8px;font-size:14px}' +
        '.label{color:#6b7280;font-weight:600}.value{font-weight:700}' +
        '.desc{font-size:14px;line-height:1.7;color:#374151;white-space:pre-wrap}' +
        '.footer{text-align:center;font-size:11px;color:#9ca3af;margin-top:32px;padding-top:16px;border-top:1px solid #e5e7eb}' +
        '@media print{body{margin:0}.no-print{display:none}}' +
        '</style></head><body>' +
        '<div class="header"><h1>AgriLeaf Disease Report</h1><p>AI-powered leaf disease analysis</p>' +
        '<span class="badge">Dept. of AI &amp; ML - Batch A8</span></div>' +
        '<div class="section"><h3>Diagnosis</h3>' +
        '<div class="row"><span class="label">Disease</span><span class="value">' + disease + '</span></div>' +
        '<div class="row"><span class="label">Crop / Pathogen</span><span class="value">' + meta + '</span></div>' +
        '<div class="row"><span class="label">Severity</span><span class="value">' + severity + '</span></div>' +
        '<div class="row"><span class="label">Confidence</span><span class="value">' + conf + '</span></div>' +
        '<div class="row"><span class="label">Scan Date</span><span class="value">' + now + '</span></div></div>' +
        '<div class="section"><h3>About this Disease</h3><p class="desc">' + desc + '</p></div>' +
        '<div class="section"><h3>Treatment</h3><p class="desc">' + (treat || 'See treatment tab in app.') + '</p></div>' +
        '<div class="footer no-print"><button onclick="window.print()" style="background:#1a3d2b;color:#fff;border:none;padding:10px 24px;border-radius:8px;font-size:14px;cursor:pointer;margin-bottom:12px">Print / Save as PDF</button><br>' +
        'Generated by AgriLeaf AI - D.Neha, D.Abhishikth, Y.Namitha, G.Meghana<br>' +
        'This report is for guidance only. Consult a local agronomist for severe cases.</div>' +
        '</body></html>';

    var blob = new Blob([html], {type: 'text/html'});
    var url = URL.createObjectURL(blob);
    var a = document.createElement('a');
    a.href = url;
    a.download = 'AgriLeaf_Report_' + Date.now() + '.html';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
}

"""

js = js[:start] + new_fn + js[end:]

with open('frontend/static/js/main.js', 'w', encoding='utf-8') as f:
    f.write(js)

print("PDF download fixed!")
print("Open the downloaded .html file in browser, then press Ctrl+P to save as PDF")